@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

Component(template, "Template", "Class")

Component(document, "Document", "Asynchronous Subroutine")

Component(resolver, "PlaceholderResolver", "Abstraction")

Component(wordUtilities, "WordUtilities", "Utility Class")

Rel(template, document, "spawns")
Rel(document, resolver, "resolves against")
Rel(document, wordUtilities, "uses")

@enduml