name: Check code
on: [push]

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run checkstyle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkMain checkTest
  owasp:
    name: owasp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run owasp dependency check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: dependencyCheckAnalyze
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run sonarqube check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: sonarqube -x test -x check
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: automatedTests
      - name: Annotate failed tests
        if: always()
        uses: ashley-taylor/junit-report-annotations-action@1.3
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}