name: Check a new push for conforming to style and security requirements

on: push

jobs:
  checkstyle:
    name: Check whether code confirms to checkstyle requirements
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run checkstyle
        uses: eskatos/gradle-command-action@v1
          with:
            arguments: checkMain checkTest
    owasp:
      name: Check whether code confirms to owasp security requirements
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v1
          with:
            java-version: 15
        - name: Run owasp dependency check
          uses: eskatos/gradle-command-action@v1
            with:
              arguments: dependencyCheckAnalyze
