name: Release new JAR to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  gradle-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build -x test -x check publish
